include(add_cxx_flag_if_supported)

macro(set_cxx11)
  if(CMAKE_VERSION VERSION_LESS "3.1")
    if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
      add_cxx_flag_if_supported("-std=c++11" CMAKE_CXX_FLAGS)
    elseif("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
      add_cxx_flag_if_supported("-std=c++11" CMAKE_CXX_FLAGS)
    elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Intel")
      add_cxx_flag_if_supported("-std=c++11" CMAKE_CXX_FLAGS)
    endif()
  else()
    set(CMAKE_CXX_STANDARD 11)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_CXX_EXTENSIONS OFF)
  endif()
endmacro(set_cxx11)
